/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject1;
import java.awt.List;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JOptionPane;
import de.javasoft.synthetica.standard.SyntheticaStandardLookAndFeel;
import java.awt.EventQueue;
import java.text.ParseException;
import javax.swing.UIManager;


/**
 *
 * @author it-server
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame1
     */
    public MainJFrame() {
        initComponents();
        setLocationRelativeTo(null);
        
        
        
  
    }
    
    //Global Database Variables {deprecated} june 26, 2023 : 11:49am
//    String jdbcDriver = "com.mysql.cj.jdbc.Driver"; //define jdbc driver
//    String dbConnectionURL = "jdbc:mysql://localhost:3306/myjavadb"; //define connection url
//    String dbUsername = "admin"; //database username
//    String dbPassword = "password"; //database password
    
    String jdbcDriver, dbConnectionURL, dbUsername, dbPassword;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfusername = new javax.swing.JTextField();
        passwordfield = new javax.swing.JPasswordField();
        registerbtn = new javax.swing.JButton();
        loginbtn = new javax.swing.JButton();
        settingsbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 51, 255), 5));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Username");

        jLabel2.setText("Password");

        tfusername.setName("TFusername"); // NOI18N

        passwordfield.setName("passwordField"); // NOI18N

        registerbtn.setText("Register");
        registerbtn.setName("registerbtn"); // NOI18N
        registerbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerbtnActionPerformed(evt);
            }
        });

        loginbtn.setText("Login");
        loginbtn.setName("loginbtn"); // NOI18N
        loginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbtnActionPerformed(evt);
            }
        });

        settingsbtn.setText("database settings");
        settingsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(loginbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(registerbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(passwordfield, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                        .addComponent(tfusername, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(99, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(settingsbtn)
                .addGap(138, 138, 138))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(passwordfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginbtn)
                    .addComponent(registerbtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(settingsbtn)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbtnActionPerformed
        // TODO add your handling code here:
        
        Connection connection = null;
        
        try {
             //create new object For DatabaseConnectionData 
            DatabaseConnectionData dbc = new DatabaseConnectionData();
            
            
            // Register the JDBC driver, retrieve from DatabaseConnectionData.java
            jdbcDriver = dbc.getJdbcDriver();
            Class.forName(jdbcDriver);
            
            
            // Provide the username and password for your MySQL installation
        
            
            String inputUsername = tfusername.getText();
            char passwordChars[] = passwordfield.getPassword();
            String inputPassword = new String(passwordChars);
            
           
            //field data retrieved from DatabaseConnectionData.java
            dbConnectionURL = dbc.getDbConnectionURL();
            dbUsername = dbc.getDbUsername();
            dbPassword = dbc.getDbPassword();
            
            
            
            // Establish the connection
            connection = DriverManager.getConnection(dbConnectionURL, dbUsername, dbPassword);
            
            // Perform database operations...
             try {
            String query = "SELECT * FROM users WHERE username = ? AND password = ?";
            PreparedStatement statement = connection.prepareStatement(query);
            statement.setString(1, inputUsername);
            statement.setString(2, inputPassword);
            
            ResultSet resultSet = statement.executeQuery();
            
            if (resultSet.next()) {
              System.out.println("Login successful!1$%^");
              setVisible(false);
              Profile profile = new Profile();
              profile.setVisible(true);
              
              System.out.println("Logged in user: " + resultSet.getString("username"));
              System.out.println("First Name: " + resultSet.getString("firstName"));
              System.out.println("Middle Name: " + resultSet.getString("middleName"));
              System.out.println("Last name: " + resultSet.getString("lastName"));
     
            } else {
                System.out.println("Invalid username or password.");
                JOptionPane.showMessageDialog(null, "Incorrect username or password!", "Warning", JOptionPane.WARNING_MESSAGE);
                passwordfield.setText(null);
            }
            
                resultSet.close();
                statement.close();
                
        } catch (SQLException e) {
            e.printStackTrace();
            
            
        }

            System.out.println("database connection successful!");
            System.out.println("==================");
            System.out.println("Entered credentials:");
            System.out.println("Username:" + inputUsername);
            System.out.println("Password:" + inputPassword);
            System.out.println("==================");
        
            
        } catch (ClassNotFoundException | SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Database Connection Failed!", "Warning", JOptionPane.WARNING_MESSAGE);
            System.out.println("Connection failed!");
            
            
        }
        
        
        
        
        
        
    }//GEN-LAST:event_loginbtnActionPerformed

    private void registerbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerbtnActionPerformed
        // TODO add your handling code here:
        
        RegisterFrame registerFrame = new RegisterFrame();
        registerFrame.setVisible(true);
        setVisible(false);
        
        
        
        
        
        
          
        
          
    }//GEN-LAST:event_registerbtnActionPerformed

    private void settingsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsbtnActionPerformed
        // TODO add your handling code here:
        DatabaseConnectionData dbc = new DatabaseConnectionData();
        dbc.setVisible(true);
        
        
    }//GEN-LAST:event_settingsbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

       // UIManager.setLookAndFeel(new SyntheticaSimple2DLookAndFeel());
       try {
          //UIManager.setLookAndFeel("de.javasoft.plaf.synthetica.SyntheticaStandardLookAndFeel");
         
       }
       catch (Exception e) {
           e.printStackTrace();
       }
       
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                DatabaseConnectionData dcd = new DatabaseConnectionData(); 
                new MainJFrame().setVisible(true);
            }
        });
        
        
       
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton loginbtn;
    private javax.swing.JPasswordField passwordfield;
    private javax.swing.JButton registerbtn;
    private javax.swing.JButton settingsbtn;
    private javax.swing.JTextField tfusername;
    // End of variables declaration//GEN-END:variables
}
